name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: create .ssh directory
      run: mkdir ~/.ssh
    - name: Verify Host via SSH
      run: ssh-keyscan 18.219.33.2 >> ~/.ssh/known_hosts
    - name: Deploy website
      env: 
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: echo $SSH_KEY > private_key
    - name: Install package
      run: npm install
    - name: Build
      run: npm run build
    - name: Give permission
      run: chmod 600 private_key
    - name: Send website
      run: scp -r -i private_key * ubuntu@18.219.33.2:/home/ubuntu/site
      
