name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: create .ssh directory
      run: mkdir ~/.ssh
    - name: Verify Host via SSH
      run: ssh-keyscan 18.219.33.2 >> ~/.ssh/known_hosts
    - name: Start SSH Agent
      run: ssh-agent -a /tmp/ssh-auth.sock
    - name: Add SSH Key to Agent
      env: 
        SSH_KEY: ${{ secrets.MASSELOT }}
        SSH_AUTH_SOCK: /tmp/ssh-auth.sock
      run: echo -n "$SSH_KEY" | ssh-add -
    - name: Install package
      run: npm install
    - name: Build
      run: npm run build
    - name: Send website
      run: scp -r dist/* ubuntu@18.219.33.2:/home/ubuntu/site
      env: 
        SSH_AUTH_SOCK: /tmp/ssh-auth.sock
